{% set version = "0.0.4" %}

package:
  name: allennlp-semparse
  version: {{ version }}

source:
  url: https://github.com/allenai/allennlp-semparse/archive/v{{ version }}.tar.gz
  sha256: 02ed9e5dc67e32dcc2d3f4ad196589f1f6e10379b78a1e2ac39f75ade62fa501

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win or py<37]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - allennlp >=2,<3
    - editdistance
    - nltk
    - parsimonious >=0.8
    - sqlparse >=0.2.4
    - unidecode

test:
  requires:
    - pytest
    - flaky
    - spacy-model-en_core_web_sm
  source_files:
    - tests/
    - test_fixtures/
  imports:
    - allennlp_semparse
  commands:
    - pytest tests

about:
  home: https://github.com/allenai/allennlp-semparse
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A framework for building semantic parsers (including neural module networks) with AllenNLP, built by the authors of AllenNLP

  doc_url: https://docs.allennlp.org/main/
  dev_url: https://github.com/allenai/allennlp-semparse

extra:
  recipe-maintainers:
    - h-vetinari
